
server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smbms?serverTimezone=UTC
    username: root
    password: ok
  jackson:
    date-format: yyyy-MM-dd



mybatis:
  configuration:
    auto-mapping-behavior: full
  type-aliases-package: com.zb.njhld.entity
  mapper-locations: classpath:mapping/*.xml